Repository toduck-App/iOS-to.duck, pull requests merged in 2024-09, with the labels that each got.

#51 feat: BaseCalendar & TDCalendarConfigurable 명확한 역할 분리 & SheetCalendar 구현
  toduck/Source/Design/Component/CalendarView/BaseCalendar.swift
  toduck/Source/Design/Component/CalendarView/Calendar/CalendarType.swift
  toduck/Source/Design/Component/CalendarView/Calendar/DiaryCalendar.swift
  toduck/Source/Design/Component/CalendarView/Calendar/SheetCalendar.swift
  toduck/Source/Design/Component/CalendarView/Calendar/TDCalendar.swift
  toduck/Source/Design/Component/CalendarView/Cell/SelectedDateType.swift
  toduck/Source/Design/Component/CalendarView/Cell/SheetCalendarSelectDateCell.swift
  toduck/Source/Design/Component/CalendarView/Common/BaseCalendar.swift
  toduck/Source/Design/Component/CalendarView/Header/CalendarHeaderStackView.swift
  toduck/Source/Design/Component/CalendarView/SheetCalendar.swift
  toduck/Source/Design/Component/TDLabel.swift
  toduck/Source/Presentation/Home/HomeViewController.swift
  toduck/Source/Presentation/Home/Toduck/ToduckViewController.swift
  toduck/Source/Presentation/Sheets/Calendar/SheetCalendarDelegate.swift
  toduck/Source/Presentation/Sheets/Calendar/SheetCalendarViewController.swift
  toduck/Source/Presentation/Sheets/Calendar/SheetCalendarViewModel.swift
  toduck/Source/Protocol/TDCalendarConfigurable.swift
Labels: ✨ feature, 🐞 fix

#52 feat: 팝업창 추가
  toduck/Source/Presentation/Common/TDPopupViewController.swift
  toduck/Source/Protocol/TDPopupPresentation.swift
Labels: ✨ feature

#54 Feat : ChipCollection 변경, Social 뷰 재사용문제 해결
  toduck/Source/Design/Component/Chip/TDChipCell.swift
  toduck/Source/Design/Component/Chip/TDChipCollectionView.swift
  toduck/Source/Design/Component/Chip/TDChipType.swift
  toduck/Source/Presentation/Common/BaseView.swift
  toduck/Source/Presentation/Common/BaseViewController.swift
  toduck/Source/Presentation/Social/SocialCoordinator.swift
  toduck/Source/Presentation/Social/SocialFeedCollectionViewCell.swift
  toduck/Source/Presentation/Social/SocialView.swift
  toduck/Source/Presentation/Social/SocialViewController.swift
Labels: ✨ feature

#55 Feat : Dropdown 컴포넌트 추가
  toduck/Source/Design/Common/TDImage.swift
  toduck/Source/Design/Component/Dropdown/TDDropdownCell.swift
  toduck/Source/Design/Component/Dropdown/TDDropdownTableView.swift
  toduck/Source/Design/Component/Dropdown/TDDropdownView.swift
  toduck/Source/Presentation/Social/SocialDropdownButton.swift
  toduck/Source/Presentation/Social/SocialView.swift
  toduck/Source/Presentation/Social/SocialViewController.swift
Labels: ✨ feature, 🖼️ design
