Repository toduck-App/iOS-to.duck, pull requests merged in 2024-12, with the labels that each got.

#64 토덕 캘린더에서 보여질 일정 & 루틴에 대한 UI 처리
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/ScheduleRepository.swift
  Projects/TDDesign/Sources/Component/Schdule/ScheduleDetailCell.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/AlarmType.swift
  Projects/TDDomain/Sources/Entity/Enum/TDCategoryColor.swift
  Projects/TDDomain/Sources/Entity/Enum/TDCategoryImageType.swift
  Projects/TDDomain/Sources/Entity/Enum/TDWeekDay.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/Entity/TDCategory.swift
  Projects/TDDomain/Sources/RepositoryProtocol/ScheduleRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/MoveTomorrowScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateScheduleUseCase.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarCoordinator.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/Home/Toduck/ToduckViewController.swift
Labels: ✨ feature

#66 TDLogger 구현
  .github/PULL_REQUEST_TEMPLATE.md
  Projects/TDCore/Sources/TDLogger.swift
Labels: ✨ feature

#63 refactor: Base ViewModel 변경에 따른 Social 변경
  Projects/TDPresentation/Sources/Common/BaseViewModel.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailViewController.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailViewModel.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListViewModel+ActionState.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListViewModel.swift
Labels: ♻️ refactor

#68 탭바 아이템 5개에서 모두 사용하는 GNB 연결
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/search_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/search_Medium.imageset/searchFillMedium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/search_Medium.imageset/searchFillMedium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/search_Medium.imageset/searchFillMedium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck_Logo.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck_Logo.imageset/toduck_Logo.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck_Logo.imageset/toduck_Logo@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck_Logo.imageset/toduck_Logo@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDPresentation/Sources/AppCoordinator.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarCoordinator.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/Common/NavigationDelegate.swift
  Projects/TDPresentation/Sources/Common/TDNavigationBarStyle.swift
  Projects/TDPresentation/Sources/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/Extension/UIViewController+ErrorAlert.swift
  Projects/TDPresentation/Sources/Extension/UIViewController+NavigationBar.swift
  Projects/TDPresentation/Sources/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/MyPage/MyPageCoordinator.swift
  Projects/TDPresentation/Sources/MyPage/MyPageViewController.swift
  Projects/TDPresentation/Sources/Protocol/Coordinator.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailCoordinator.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/Tabbar/TabBarCoordinator.swift
  Projects/TDPresentation/Sources/Timer/TimerCoordinator.swift
  Projects/TDPresentation/Sources/Timer/TimerViewController.swift
  Projects/toduck/Sources/SceneDelegate.swift
Labels: ✨ feature, 🖼️ design

#72 카테고리 이미지 13개 & Body3 폰트 추가
  Projects/TDDesign/Resources/Images.xcassets/Category/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryComputer.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryComputer.imageset/categoryComputer.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryComputer.imageset/categoryComputer@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryComputer.imageset/categoryComputer@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryFood.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryFood.imageset/categoryFood.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryFood.imageset/categoryFood@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryFood.imageset/categoryFood@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryHeart.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryHeart.imageset/categoryHeart.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryHeart.imageset/categoryHeart@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryHeart.imageset/categoryHeart@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryMedicine.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryMedicine.imageset/categoryMedicine.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryMedicine.imageset/categoryMedicine@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryMedicine.imageset/categoryMedicine@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryNone.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryNone.imageset/categoryNone.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryNone.imageset/categoryNone@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryNone.imageset/categoryNone@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPencil.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPencil.imageset/categoryPencil.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPencil.imageset/categoryPencil@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPencil.imageset/categoryPencil@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPeople.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPeople.imageset/categoryPeople.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPeople.imageset/categoryPeople@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPeople.imageset/categoryPeople@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPower.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPower.imageset/categoryPower.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPower.imageset/categoryPower@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryPower.imageset/categoryPower@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryRedbook.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryRedbook.imageset/categoryRedbook.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryRedbook.imageset/categoryRedbook@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryRedbook.imageset/categoryRedbook@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categorySleep.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categorySleep.imageset/categorySleep.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categorySleep.imageset/categorySleep@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categorySleep.imageset/categorySleep@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryTalk.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryTalk.imageset/categoryTalk.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryTalk.imageset/categoryTalk@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryTalk.imageset/categoryTalk@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryVehicle.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryVehicle.imageset/categoryVehicle.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryVehicle.imageset/categoryVehicle@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryVehicle.imageset/categoryVehicle@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryYellowbook.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryYellowbook.imageset/categoryYellowbook.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryYellowbook.imageset/categoryYellowbook@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Category/categoryYellowbook.imageset/categoryYellowbook@3x.png
  Projects/TDDesign/Sources/Common/TDFont.swift
Labels: 🖼️ design

#73 홈 탭바의 일정 & 루틴 세그먼트에 대한 UI 작업
  Projects/TDData/Sources/Repository/PostRepositoryImpl.swift
  Projects/TDData/Sources/Repository/RoutineRepository.swift
  Projects/TDData/Sources/Repository/ScheduleRepository.swift
  Projects/TDDesign/Sources/Common/TDColor+Extension.swift
  Projects/TDDesign/Sources/Common/TDColor+Pair.swift
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Calendar/CalendarView/DiaryCalendar.swift
  Projects/TDDesign/Sources/Component/Calendar/CalendarView/HomeCalendar.swift
  Projects/TDDesign/Sources/Component/Calendar/CalendarView/SheetCalendar.swift
  Projects/TDDesign/Sources/Component/Calendar/CalendarView/ToduckCalendar.swift
  Projects/TDDesign/Sources/Component/Calendar/Common/BaseCalendar.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/Entity/Post.swift
  Projects/TDDomain/Sources/Entity/Protocol/Eventable.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/Entity/TDCategory.swift
  Projects/TDPresentation/Sources/Calendar/SelectedDayScheduleView.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/Common/BaseView.swift
  Projects/TDPresentation/Sources/Common/BaseViewController.swift
  Projects/TDPresentation/Sources/Extension/Eventable+Presentation.swift
  Projects/TDPresentation/Sources/Extension/TDCategoryColor+UIColor.swift
  Projects/TDPresentation/Sources/Extension/TDCategoryImageType+UIImage.swift
  Projects/TDPresentation/Sources/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/Home/Routine/RoutineViewController.swift
  Projects/TDPresentation/Sources/Home/Schedule/ScheduleViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/Cell/TimeSlotTableViewCell.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/PresentModel/TimeSlot.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/PresentModel/TimeSlotProvider.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/RoutineViewModel.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/Social/Common/View/SocialRoutineView.swift
Labels: ✨ feature
