Repository toduck-App/iOS-to.duck, pull requests merged in 2025-01, with the labels that each got.

#75 홈 탭바의 일정&루틴 세그먼트에서 일정추가 UI 및 연결 로직 구현
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/add_Medium.imageset/Ic=Add, Size=Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/add_Medium.imageset/Ic=Add, Size=Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/add_Medium.imageset/Ic=Add, Size=Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/addSmall.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/addSmall.imageset/addLarge.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/addSmall.imageset/addLarge@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/addSmall.imageset/addLarge@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/add_Small.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/add_Small.imageset/Ic=Add, Size=Small.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/add_Small.imageset/Ic=Add, Size=Small@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/add_Small.imageset/Ic=Add, Size=Small@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Button/TDButton.swift
  Projects/TDDesign/Sources/Component/TextField/TDTextField.swift
  Projects/TDPresentation/Sources/Common/BaseView.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
Labels: ✨ feature

#84 UserDefaults로부터 카테고리 색상 조회 & 변경 로직 구현 + 테스트 코드 작성
  Projects/TDCore/Project.swift
  Projects/TDCore/Sources/TDDataError.swift
  Projects/TDData/Project.swift
  Projects/TDData/Sources/DTO/TDCategoryDTO.swift
  Projects/TDData/Sources/Repository/CategoryRepositoryImpl.swift
  Projects/TDData/Sources/StorageProtocol/CategoryStorage.swift
  Projects/TDData/Tests/CategoryRepositoryTests.swift
  Projects/TDData/Tests/DataTest.swift
  Projects/TDData/Tests/Mock/MockCategoryStorage.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/TDCategory.swift
  Projects/TDDomain/Sources/RepositoryProtocol/CategoryRepository.swift
  Projects/TDDomain/Sources/UseCase/UpdateCategoryUseCase.swift
  Projects/TDDomain/Tests/DomainTest.swift
  Projects/TDDomain/Tests/FetchCategoriesUseCaseTests.swift
  Projects/TDDomain/Tests/Mock/MockCategoryRepository.swift
  Projects/TDDomain/Tests/UpdateCategoriesUseCaseTests.swift
  Projects/TDPresentation/Project.swift
  Projects/TDPresentation/Sources/Sheets/Color/SheetColorCoordinator.swift
  Projects/TDPresentation/Sources/Sheets/Color/SheetColorViewController.swift
  Projects/TDPresentation/Sources/Sheets/Color/SheetColorViewModel.swift
  Projects/TDPresentation/Tests/Mock/MockFetchCategoriesUseCase.swift
  Projects/TDPresentation/Tests/Mock/MockUpdateCategoriesUseCase.swift
  Projects/TDPresentation/Tests/PresentationTest.swift
  Projects/TDPresentation/Tests/SheetColorViewModelTests.swift
  Projects/TDStorage/Project.swift
  Projects/TDStorage/Sources/UserDefaults/CategoryStorage.swift
  Projects/TDStorage/Tests/CategoryStorageTests.swift
  Projects/TDStorage/Tests/StroageTest.swift
Labels: ✨ feature

#86 각 모듈의 테스트 타겟에서 의존성 문제 해결
  Projects/TDData/Project.swift
  Projects/TDDomain/Project.swift
  Projects/TDPresentation/Project.swift
  Projects/TDStorage/Project.swift
Labels: 🐞 fix

#90 #79 - #88 마이페이지 메인 화면 구현
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium.imageset/Ic=_Pen, Size=Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium.imageset/Ic=_Pen, Size=Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium.imageset/Ic=_Pen, Size=Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium_Color.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium_Color.imageset/pen_Medium_Color@1x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium_Color.imageset/pen_Medium_Color@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Medium_Color.imageset/pen_Medium_Color@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium.imageset/Ic=Camera, Size=Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium.imageset/Ic=Camera, Size=Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium.imageset/Ic=Camera, Size=Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium_Color.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium_Color.imageset/Icon.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium_Color.imageset/Icon@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/camera_Medium/camera_Medium_Color.imageset/Icon@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Form/TDFormPhotoView.swift
  Projects/TDDesign/Sources/ViewControllers/TDPhotoPickerController.swift
  Projects/TDPresentation/Sources/Common/BaseView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Cell/MyPageMenuCollectionFooterView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Cell/MyPageMenuCollectionHeaderView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Cell/MyPageMenuCollectionViewCell.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Common/TDImageView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Custom/CustomEventWrapper.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/Custom/CustomScrollView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MainPage/BadgeLabel.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MainPage/FollowInfoView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MainPage/MyPageMenuContainer.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MainPage/MyPageProfileView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MainPage/MyPageSocialButtonView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MyPageView.swift
  Projects/TDPresentation/Sources/MyPage/MyPageView/MyPageViewController.swift
  Projects/TDPresentation/Sources/MyPage/MyPageViewController.swift
  Projects/TDPresentation/Sources/Tabbar/MainTabBarController.swift
Labels: 🖼️ design

#97 #92 네트워크 레이어 구현
  Projects/TDNetwork/Project.swift
  Projects/TDNetwork/Sources/Network/API/AuthAPI.swift
  Projects/TDNetwork/Sources/Network/API/DiaryAPI.swift
  Projects/TDNetwork/Sources/Network/API/RoutineAPI.swift
  Projects/TDNetwork/Sources/Network/API/ScheduleAPI.swift
  Projects/TDNetwork/Sources/Network/API/SocialAPI.swift
  Projects/TDNetwork/Sources/Network/API/TimerAPI.swift
  Projects/TDNetwork/Sources/Network/MF/Extensions/Extension+Encodable.swift
  Projects/TDNetwork/Sources/Network/MF/Extensions/Extension+Result.swift
  Projects/TDNetwork/Sources/Network/MF/Extensions/Extension+URLRequest.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MF.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFError.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFHTTPMethod.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFHeaders.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFRequest.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFResponse.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFSession.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFURLConvertible.swift
  Projects/TDNetwork/Sources/Network/MF/Target/MFProvider.swift
  Projects/TDNetwork/Sources/Network/MF/Target/MFTarget.swift
  Projects/TDNetwork/Sources/Network/MF/Target/MFTask.swift
  Projects/TDNetwork/Sources/Network/Moya/DiaryTarget.swift
  Projects/TDNetwork/Sources/Network/Moya/TimerTarget.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feature
