Repository toduck-App/iOS-to.duck, pull requests merged in 2025-04, with the labels that each got.

#185 일기 탭바의 일기와 집중 캘린더 UI 구조 분리
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookDecrease.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookDecrease.imageset/bookDecrease.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookDecrease.imageset/bookDecrease@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookDecrease.imageset/bookDecrease@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookPercent0.imageset/bookPercent0.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookPercent0.imageset/bookPercent0@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookPercent0.imageset/bookPercent0@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/clockFill.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/clockFill.imageset/clockFill.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/clockFill.imageset/clockFill@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/clockFill.imageset/clockFill@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/diaryNavigation.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/diaryNavigation.imageset/diaryNavigation.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/diaryNavigation.imageset/diaryNavigation@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/diaryNavigation.imageset/diaryNavigation@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Calendar/CalendarView/CalendarType.swift
  Projects/TDDesign/Sources/Component/Calendar/Cell/DiaryCalendarSelectDateCell.swift
  Projects/TDDesign/Sources/Component/Calendar/Header/CalendarHeaderStackView.swift
  Projects/TDDesign/Sources/Component/Calendar/Header/PickerButton.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryDetailView.swift
  Projects/TDDesign/Sources/Component/Diary/FocusDetailView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextField.swift
  Projects/TDDesign/Sources/Component/TextField/TDTextField.swift
  Projects/TDDomain/Sources/Entity/Focus.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryEditType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MainPage/MyPageProfileView.swift
Labels: ♻️ refactor

#168 타이머 로직 수정 및 휴식 타이머 추가
  Projects/TDDesign/Resources/LottieJSON/Timer/Timer_0.json
  Projects/TDDesign/Resources/LottieJSON/Timer/Timer_1.json
  Projects/TDDesign/Resources/LottieJSON/Timer/Timer_2.json
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Timer.swift
  Projects/TDDomain/Sources/UseCase/Timer/FocusTimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/PauseTimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/RestTimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/TimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateFocusCountUseCase.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/ThemeSetting/ThemeSettingView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerSetting/TimerSettingView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerSetting/TimerSettingViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/View/BaseTimerView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/View/BboduckTimerView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/View/SimpleTimerView.swift
  Projects/TDPresentation/Sources/Protocol/TDToastPresentable.swift
Labels: ✨ feature

#192 일기 탭바 - 기분 CRUD 구현
  Projects/TDData/Sources/DTO/DiaryCompareCountResponseDTO.swift
  Projects/TDData/Sources/DTO/DiaryListResponseDTO.swift
  Projects/TDData/Sources/DTO/DiaryPatchRequestDTO.swift
  Projects/TDData/Sources/DTO/DiaryPostRequestDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/DiaryRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/DiaryService.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryDetailView.swift
  Projects/TDDesign/Sources/Component/Dropdown/TDDropdownCell.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Diary.swift
  Projects/TDDomain/Sources/RepositoryProtocol/DiaryRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateDiaryUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteDiaryUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchDiaryCompareCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchDiaryListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchDiaryUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateDiaryUseCase.swift
  Projects/TDNetwork/Sources/Network/API/DiaryAPI.swift
  Projects/TDNetwork/Sources/Service/DiaryServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DeleteEvent/DeleteEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryEditType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabbarItem.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/SocialFeedMoreType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/SocialSortType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewController.swift
  Projects/toduck/Resources/Assets.xcassets/launchScreenPrimaryImage.imageset/Contents.json
  Projects/toduck/Resources/Assets.xcassets/launchScreenPrimaryImage.imageset/launchScreenPrimaryImage.png
  Projects/toduck/Resources/Assets.xcassets/launchScreenPrimaryImage.imageset/launchScreenPrimaryImage@2x.png
  Projects/toduck/Resources/Assets.xcassets/launchScreenPrimaryImage.imageset/launchScreenPrimaryImage@3x.png
  Projects/toduck/Resources/LaunchScreen.storyboard
  Projects/toduck/SupportingFiles/Info.plist
Labels: ✨ feature

#191 홈 탭바의 토덕 세그먼트에서 일정 조회 및 비즈니스 로직 처리
  Projects/TDCore/Sources/Date+DateFormatType.swift
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/NoRecord.imageset/NoRecord_Image@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/noEventImage.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/noEventImage.imageset/noEventImage.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/noEventImage.imageset/noEventImage@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/noEventImage.imageset/noEventImage@3x.png
  Projects/TDDesign/Resources/LottieJSON/Schedule/toduckComputer.json
  Projects/TDDesign/Resources/LottieJSON/Schedule/toduckDrive.json
  Projects/TDDesign/Resources/LottieJSON/Schedule/toduckHeart.json
  Projects/TDDesign/Resources/LottieJSON/Schedule/toduckMedicine.json
  Projects/TDDesign/Resources/LottieJSON/Schedule/toduckNotodo.json
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Category/ColorPalette/TDCategoryColorPaletteView.swift
  Projects/TDDesign/Sources/Component/Category/TDCategoryCollectionView.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryMoodCollectionView.swift
  Projects/TDDesign/Sources/Component/SegmentedControl/TDSegmentedControl.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Sources/UseCase/ShouldMarkAllDayUseCase.swift
  Projects/TDDomain/Tests/FetchScheduleListUseCaseTests.swift
  Projects/TDDomain/Tests/Mock/MockScheduleRepository.swift
  Projects/TDDomain/Tests/ShouldMarkAllDayUseCaseTests.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Information/EditInformationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Menu/EditProfileMenuCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Menu/EditProfileMenuViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Color/SheetColorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/toduck/Sources/SceneDelegate.swift
Labels: ✨ feature

#198 홈 탭바의 '루틴' 세그먼트의 루틴 관련 CRUD API 연결
  Projects/TDData/Sources/DTO/RoutineAvailableListResponseDTO.swift
  Projects/TDData/Sources/DTO/RoutineListResponseDTO.swift
  Projects/TDData/Sources/DTO/RoutineRequestDTO.swift
  Projects/TDData/Sources/DTO/RoutineResponseDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/RoutineService.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextField.swift
  Projects/TDDesign/Sources/Component/TextField/TDTextField.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/AlarmType.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/RepositoryProtocol/RoutineRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchAvailableRoutineListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchRoutineListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateCompletionRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateRoutineUseCase.swift
  Projects/TDNetwork/Sources/Network/API/RoutineAPI.swift
  Projects/TDNetwork/Sources/Service/RoutineServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/RoutineSelect/SocialSelectRoutineCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/RoutineSelect/SocialSelectRoutineViewModel.swift
Labels: ✨ feature

#199 일정과 루틴을 각각 보여주던 구조에서 '투두'로 합쳐 함께 보이도록 UI 리팩토링
  Projects/TDCore/Sources/Date+DateFormatType.swift
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Dot/dotVerticalGap.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Dot/dotVerticalGap.imageset/dotGap.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Dot/dotVerticalGap.imageset/dotGap@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Dot/dotVerticalGap.imageset/dotGap@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/check_Neutral.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/check_Neutral.imageset/check_Neutral.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/check_Neutral.imageset/check_Neutral@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/check_Neutral.imageset/check_Neutral@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/cycleImage.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/cycleImage.imageset/cycleImage.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/cycleImage.imageset/cycleImage@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/cycleImage.imageset/cycleImage@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Button/TDBaseButton.swift
  Projects/TDDesign/Sources/Component/Button/TDSelectableButton.swift
  Projects/TDDesign/Sources/Component/Category/TDCategoryCollectionView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormSegmentView.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/Entity/Enum/TDEventMode.swift
  Projects/TDDomain/Sources/Entity/Protocol/Eventable.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/Entity/TDCategory.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/Cell/TimeSlotGapCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/Cell/TimeSlotTableViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/TodoViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/View/FloatingActionMenuView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ViewModel/RoutineViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/RoutineSelect/Cell/SocialRoutineSelectCell.swift
  Projects/TDPresentation/Sources/Common/BaseViewController+ErrorAlert.swift
  Projects/TDPresentation/Sources/Common/TDPopupViewController.swift
  Projects/TDPresentation/Sources/PresentModel/EventDisplayItem.swift
  Projects/TDPresentation/Sources/PresentModel/EventPresentable.swift
  Projects/TDPresentation/Sources/PresentModel/Eventable+Presentation.swift
  Projects/TDPresentation/Sources/PresentModel/TimeSlot/TimeSlot.swift
  Projects/TDPresentation/Sources/PresentModel/TimeSlot/TimeSlotProvider.swift
Labels: ♻️ refactor

#203 일정과 루틴을 함께 받아 투두 화면에서 함께 보여주도록 UI 리팩토링
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDData/Sources/DTO/ScheduleUpdateRequestDTO.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/Repository/ScheduleRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/RoutineService.swift
  Projects/TDData/Sources/ServiceProtocol/ScheduleService.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/RepositoryProtocol/RoutineRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/ScheduleRepository.swift
  Projects/TDDomain/Sources/UseCase/FinishRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/FinishScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateCompletionRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateScheduleUseCase.swift
  Projects/TDNetwork/Sources/Network/API/RoutineAPI.swift
  Projects/TDNetwork/Sources/Network/API/ScheduleAPI.swift
  Projects/TDNetwork/Sources/Service/RoutineServiceImpl.swift
  Projects/TDNetwork/Sources/Service/ScheduleServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EditScheduleModeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/Cell/TimeSlotGapCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/Cell/TimeSlotTableViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/View/FloatingActionMenuView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/PresentModel/EventDisplayItem.swift
  Projects/TDPresentation/Sources/PresentModel/Eventable+Presentation.swift
Labels: ✨ feature, ♻️ refactor

#205 Social API 2
  Projects/TDData/Sources/DTO/RoutineListResponseDTO.swift
  Projects/TDData/Sources/DTO/TDPostDTO.swift
  Projects/TDData/Sources/DTO/TDRoutineDTO.swift
  Projects/TDData/Sources/DTO/TDUserProfileResponseDTO.swift
  Projects/TDData/Sources/Repository/SocialRepositoryImp.swift
  Projects/TDData/Sources/Repository/UserRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/SocialService.swift
  Projects/TDData/Sources/ServiceProtocol/UserService.swift
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background1.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background1.imageset/social_profile_background1.png
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background1.imageset/social_profile_background1@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background1.imageset/social_profile_background1@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background2.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background2.imageset/social_profile_background2.png
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background2.imageset/social_profile_background2@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Profile_Image/profile_background2.imageset/social_profile_background3@2x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/ReportType.swift
  Projects/TDDomain/Sources/Entity/UserDetail.swift
  Projects/TDDomain/Sources/RepositoryProtocol/SocialRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/UserRepository.swift
  Projects/TDDomain/Sources/UseCase/BlockCommentUseCase.swift
  Projects/TDDomain/Sources/UseCase/BlockPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteCommentUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchUserPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/ReportPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/ShareRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/ToggleCommentUseCase.swift
  Projects/TDNetwork/Sources/Network/API/SocialAPI.swift
  Projects/TDNetwork/Sources/Service/SocialServiceImpl.swift
  Projects/TDNetwork/Sources/Service/UserServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialRoutineView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/Cell/SocialDetailCommentCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/ReportType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportDetailViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/RoutineSelect/Cell/SocialRoutineSelectCell.swift
Labels: ✨ feature

#201 일기 탭바의 집중 세그먼트 - 집중 리스트를 받아와 캘린더에 표시 및 이번 달 집중 퍼센트 API 연결
  Projects/TDData/Sources/DTO/FocusListResponseDTO.swift
  Projects/TDData/Sources/DTO/FocusPercentResponseDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/DiaryRepositoryImpl.swift
  Projects/TDData/Sources/Repository/FocusRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/DiaryService.swift
  Projects/TDData/Sources/ServiceProtocol/FocusService.swift
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus1to20.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus1to20.imageset/focus1to20.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus1to20.imageset/focus1to20@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus1to20.imageset/focus1to20@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus21to40.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus21to40.imageset/focus21to40.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus21to40.imageset/focus21to40@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus21to40.imageset/focus21to40@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus41to70.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus41to70.imageset/focus41to70.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus41to70.imageset/focus41to70@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus41to70.imageset/focus41to70@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus71to100.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus71to100.imageset/focus71to100.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus71to100.imageset/focus71to100@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focus71to100.imageset/focus71to100@3x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focusZero.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focusZero.imageset/focusZero.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focusZero.imageset/focusZero@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/focusZero.imageset/focusZero@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/RepositoryProtocol/DiaryRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/FocusRepository.swift
  Projects/TDDomain/Sources/UseCase/FetchDiaryCompareCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchFocusListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchFocusPercentUseCase.swift
  Projects/TDNetwork/Sources/Network/API/FocusAPI.swift
  Projects/TDNetwork/Sources/Service/DiaryServiceImpl.swift
  Projects/TDNetwork/Sources/Service/FocusServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewModel.swift
Labels: ✨ feature

#200 일기 작성 시 사진 추가 기능 구현
  Projects/TDData/Sources/DTO/DiaryPatchRequestDTO.swift
  Projects/TDData/Sources/DTO/DiaryPostRequestDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/DiaryRepositoryImpl.swift
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookZero.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookZero.imageset/bookZero.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookZero.imageset/bookZero@2x.png
  Projects/TDDesign/Resources/Images.xcassets/DiaryAnalyze/bookZero.imageset/bookZero@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Calendar/Header/CalendarHeaderStackView.swift
  Projects/TDDesign/Sources/Component/Calendar/Header/PickerButton.swift
  Projects/TDDomain/Sources/RepositoryProtocol/DiaryRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateDiaryUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateDiaryUseCase.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/Analyze/DiaryAnalyzeDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryDetailView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialImageListView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/Common/DetailImage/DetailImageCell.swift
  Projects/TDPresentation/Sources/Common/DetailImage/DetailImageViewController.swift
  Projects/TDPresentation/Sources/Common/DetailImage/ImagePageViewController.swift
  Projects/TDPresentation/Sources/Extension/UIView+FindViewController.swift
  Projects/TDPresentation/Sources/Extension/UIView+Spacer.swift
Labels: ✨ feature

#208 토덕 메인 캘린더 UI 리팩토링 및 API 연결
  Projects/TDCore/Sources/Calendar+GenerateDates.swift
  Projects/TDCore/Sources/Date+DateFormatType.swift
  Projects/TDCore/Sources/Date+StripTime.swift
  Projects/TDCore/Sources/Date+TimeSortHelper.swift
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/Ic=X1, Size=Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/Ic=X1, Size=Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/Ic=X1, Size=Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium@3x.png
  Projects/TDDesign/Sources/Component/Calendar/Header/CalendarHeaderStackView.swift
  Projects/TDDesign/Sources/Component/Calendar/Header/PickerButton.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormMoveView.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/UseCase/BuildMonthScheduleDictUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Tests/FetchScheduleListUseCaseTests.swift
  Projects/TDDomain/Tests/Mock/MockScheduleRepository.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/Cell/ScheduleDetailCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/View/SelectedDayScheduleView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/FocusCalendar/FocusCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Calendar/SheetCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Time/SheetTimeView.swift
Labels: ✨ feature, ♻️ refactor

#214 소셜 API 3
  Projects/TDData/Sources/DTO/RoutineListResponseDTO.swift
  Projects/TDData/Sources/DTO/TDPostDTO.swift
  Projects/TDData/Sources/DTO/TDRoutineDTO.swift
  Projects/TDData/Sources/Repository/SocialRepositoryImp.swift
  Projects/TDData/Sources/ServiceProtocol/SocialService.swift
  Projects/TDDesign/Sources/Component/Chip/TDChipCollectionView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextField.swift
  Projects/TDDomain/Sources/RepositoryProtocol/SocialRepository.swift
  Projects/TDDomain/Sources/UseCase/ReportCommentUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdatePostUseCase.swift
  Projects/TDNetwork/Sources/Network/API/SocialAPI.swift
  Projects/TDNetwork/Sources/Network/MF/Extensions/Extension+URLRequest.swift
  Projects/TDNetwork/Sources/Service/SocialServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Delegates/SocialPostDelegate.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialHeaderView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/Cell/SocialDetailCommentCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/Cell/SocialDetailPostCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/Cell/SocialFeedCollectionViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportDetailViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Report/SocialReportViewModel.swift
  Projects/TDPresentation/Sources/Common/BaseViewController+ErrorAlert.swift
  Projects/TDPresentation/Sources/Extension/NavigationController+PushViewController.swift
Labels: ✨ feature

#213 중복 클릭 방지를 위한 버튼, Throttle 적용
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewModel.swift
Labels: ♻️ refactor

#211 일정과 루틴 이벤트에 대한 수정 및 삭제 API 연결
  Projects/TDData/Sources/DTO/RoutineListResponseDTO.swift
  Projects/TDData/Sources/DTO/RoutineRequestDTO.swift
  Projects/TDData/Sources/DTO/RoutineResponseDTO.swift
  Projects/TDData/Sources/DTO/RoutineUpdateRequestDTO.swift
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDData/Sources/DTO/ScheduleRequestDTO.swift
  Projects/TDData/Sources/DTO/ScheduleUpdateRequestDTO.swift
  Projects/TDData/Sources/DTO/TDRoutineDTO.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/Repository/ScheduleRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/RoutineService.swift
  Projects/TDData/Sources/ServiceProtocol/ScheduleService.swift
  Projects/TDDesign/Sources/Common/TDFont.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/AlarmTime.swift
  Projects/TDDomain/Sources/Entity/Protocol/Eventable.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/RepositoryProtocol/RoutineRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/ScheduleRepository.swift
  Projects/TDDomain/Sources/UseCase/DeleteScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateRoutineUseCase.swift
  Projects/TDNetwork/Sources/Network/API/RoutineAPI.swift
  Projects/TDNetwork/Sources/Network/API/ScheduleAPI.swift
  Projects/TDNetwork/Sources/Service/RoutineServiceImpl.swift
  Projects/TDNetwork/Sources/Service/ScheduleServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DeleteEvent/DeleteEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EditScheduleModeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/Cell/TimeSlotTableViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialRoutineView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/TimelineRoutineCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/RoutineSelect/Cell/SocialRoutineSelectCell.swift
  Projects/TDPresentation/Sources/Extension/Eventable+UI.swift
  Projects/TDPresentation/Sources/PresentModel/EventDisplayItem.swift
  Projects/TDPresentation/Sources/PresentModel/EventPresentable.swift
Labels: ✨ feature

#219 플로팅 버튼이 첫 윈도우 화면에 계속 띄워져 다른 버튼을 가리는 문제해결
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x1_Medium.imageset/x1_Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/Ic=X2, Size=Medium.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/Ic=X2, Size=Medium@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/Ic=X2, Size=Medium@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/x2.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/x2@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/X/x2_Medium.imageset/x2@3x.png
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DeleteEvent/DeleteEventView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DeleteEvent/DeleteEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCalendar/DiaryCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/SocialFeedMoreType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
Labels: 🐞 fix
