Repository toduck-App/iOS-to.duck, pull requests merged in 2025-05, with the labels that each got.

#222 '홈' 탭바의 '투두' 세그먼트 - 주간 캘린더 투두 조회 로직 개선
  Projects/TDCore/Project.swift
  Projects/TDData/Sources/DTO/RoutineListForDatesResponseDTO.swift
  Projects/TDData/Sources/DTO/RoutineListResponseDTO.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/RoutineService.swift
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/RepositoryProtocol/RoutineRepository.swift
  Projects/TDDomain/Sources/UseCase/BuildMonthScheduleDictUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteRoutineAfterCurrentDayUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteRoutineForCurrentDayUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchRoutineListForDatesUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Tests/FetchScheduleListUseCaseTests.swift
  Projects/TDDomain/Tests/Mock/MockScheduleRepository.swift
  Projects/TDNetwork/Sources/Network/API/RoutineAPI.swift
  Projects/TDNetwork/Sources/Service/RoutineServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Todo/TodoViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewModel.swift
Labels: ♻️ refactor

#228 Push Notifications 설정 및 집중 타이머 로컬 푸쉬알림 로직 구현
  Projects/TDCore/Sources/Notification/LocalNotificationType.swift
  Projects/TDCore/Sources/Notification/LocalPushNotificationManager.swift
  Projects/TDDomain/Sources/Entity/Timer.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/Cell/MyPageMenuCollectionHeaderView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/Cell/MyPageMenuCollectionViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MainPage/MyPageMenuContainer.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MainPage/MyPageSocialButtonView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Time/SheetTimeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/Popup/TimerCautionPopupView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewModel.swift
  Projects/toduck/Sources/AppDelegate.swift
  Projects/toduck/SupportingFiles/Info.plist
  Projects/toduck/SupportingFiles/toduck.entitlements
Labels: ✨ feature

#227 hotfix: Info.plist LaunchScreen 확장자명 제거
  Projects/toduck/SupportingFiles/Info.plist
Labels: 🐞 fix

#232 온보딩, 코치마크 뷰
  Projects/TDCore/Sources/TDTokenManager.swift
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_First.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_First.imageset/_coachMark1.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_First.imageset/_coachMark1@2x.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_First.imageset/_coachMark1@3x.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Second.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Second.imageset/coachMark2.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Second.imageset/coachMark2@2x.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Second.imageset/coachMark2@3x.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Third.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Third.imageset/coachMark3.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Third.imageset/coachMark3@2x.png
  Projects/TDDesign/Resources/Images.xcassets/CoachMark/coachMark_Third.imageset/coachMark3@3x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_First.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_First.imageset/WalkThrough.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_First.imageset/WalkThrough@2x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_First.imageset/WalkThrough@3x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Second.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Second.imageset/WalkThrough1.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Second.imageset/WalkThrough1@2x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Second.imageset/WalkThrough1@3x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Third.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Third.imageset/WalkThrough2.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Third.imageset/WalkThrough2@2x.png
  Projects/TDDesign/Resources/Images.xcassets/WalkThrough/WalkThrough_Third.imageset/WalkThrough2@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/DotIndicator/TDDotIndicator.swift
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Coach/CoachCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Coach/CoachView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Coach/CoachViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/OnboardingFlow/WalkThroughCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/OnboardingFlow/WalkThroughView.swift
  Projects/TDPresentation/Sources/AppFlow/OnboardingFlow/WalkThroughViewController.swift
Labels: ✨ feature

#233 코디네이터 패턴에서 노티의 딥링크 유형에 따른 화면이동 처리
  .gitignore
  Projects/TDCore/Sources/DeepLinkType.swift
  Projects/TDNetwork/Sources/Service/AuthServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MainPage/MyPageMenuContainer.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Notification/NotificationCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Notification/NotificationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileCoordinator.swift
  Projects/toduck/Project.swift
  Projects/toduck/Sources/AppDelegate.swift
  Projects/toduck/Sources/SceneDelegate.swift
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feature

#242 chore: 문구 수정
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/PrivacyPolicy/PrivacyPolicyView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/TermsOfUse/TermOfUseView.swift
  Projects/toduck/SupportingFiles/Info.plist
Labels: 🐞 fix, ♻️ refactor

#247 회원탈퇴 UI 레이아웃 수정
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionView.swift
Labels: ⚒️ chore
