Repository toduck-App/iOS-to.duck, pull requests merged in 2025-03, with the labels that each got.

#139 자체 로그인 API 연결 & 구조적 동시성을 통해 로그인 정보를 KeyChain에 저장 로직 구현
  Projects/TDCore/Sources/KeyChain/KeyChainConstant.swift
  Projects/TDCore/Sources/KeyChain/KeyChainError.swift
  Projects/TDCore/Sources/KeyChain/KeyChainManager.swift
  Projects/TDCore/Sources/TDDataError.swift
  Projects/TDData/Sources/DTO/LoginUserRepsonseDTO.swift
  Projects/TDData/Sources/Repository/AuthRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/AuthService.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/RepositoryProtocol/AuthRepository.swift
  Projects/TDDomain/Sources/UseCase/LoginUseCase.swift
  Projects/TDNetwork/Sources/Network/API/AuthAPI.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFError.swift
  Projects/TDNetwork/Sources/Service/AuthServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewModel.swift
Labels: ✨ feature

#141 카카오 로그인을 위한 Tuist 환경 설정 및 UI, 로직 구현
  Projects/TDCore/Project.swift
  Projects/TDData/Sources/Repository/AuthRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/AuthService.swift
  Projects/TDDesign/Project.swift
  Projects/TDDesign/Resources/Colors.xcassets/Colors/Oauth/Contents.json
  Projects/TDDesign/Resources/Colors.xcassets/Colors/Oauth/kakao_background.colorset/Contents.json
  Projects/TDDesign/Resources/Colors.xcassets/Colors/Oauth/kakao_foreground.colorset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginBackGround.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginBackGround.imageset/loginBackGround.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginBackGround.imageset/loginBackGround@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginBackGround.imageset/loginBackGround@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginToduck.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginToduck.imageset/LoginToduck.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginToduck.imageset/LoginToduck@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/LoginToduck.imageset/LoginToduck@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Logo.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Logo.imageset/toduck_Logo.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Logo.imageset/toduck_Logo@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Logo.imageset/toduck_Logo@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Primary_Logo.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Primary_Logo.imageset/Toduck_Primary_Logo.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Primary_Logo.imageset/Toduck_Primary_Logo@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/Toduck_Primary_Logo.imageset/Toduck_Primary_Logo@3x.png
  Projects/TDDesign/Sources/Common/TDColor.swift
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/AuthProvider.swift
  Projects/TDDomain/Sources/RepositoryProtocol/AuthRepository.swift
  Projects/TDDomain/Sources/UseCase/AppleLoginUseCase.swift
  Projects/TDDomain/Sources/UseCase/KakaoLoginUseCase.swift
  Projects/TDNetwork/Project.swift
  Projects/TDNetwork/Sources/Network/API/AuthAPI.swift
  Projects/TDNetwork/Sources/Service/AuthServiceImpl.swift
  Projects/TDPresentation/Project.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewModel.swift
  Projects/toduck/Sources/AppDelegate.swift
  Projects/toduck/Sources/SceneDelegate.swift
  Projects/toduck/SupportingFiles/Info.plist
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feature

#143 로그인/회원가입 UI 변경사항 수정 & 로그인 실패 시 토스트 메세지 표시
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewController.swift
Labels: ♻️ refactor

#149 KeychainManager-KJ SPM 의존성 추가에 따른 리팩토링
  Projects/TDCore/Project.swift
  Projects/TDCore/Sources/KeyChain+Constant.swift
  Projects/TDCore/Sources/KeyChain/KeyChainError.swift
  Projects/TDCore/Sources/KeyChain/KeyChainManager.swift
  Projects/TDData/Sources/Repository/AuthRepositoryImpl.swift
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ♻️ refactor

#150 fix: 아카이브할 때 Info.plist 오류 개선
  Projects/toduck/SupportingFiles/Info.plist
Labels: 🐞 fix

#154 UIControl을 상속받아 커스텀 TDSegmentedControl 구현 및 리팩토링
  Projects/TDDesign/Sources/Component/SegmentedControl/TDSegmentedControl.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindAccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/SocialProfileViewController.swift
Labels: ♻️ refactor

#156 잘못된 코디네이터 패턴 사용에 따른 강한 참조 사이클 & 자식 코디네이터 관리 누락 문제해결
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindAccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/EditProfileCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/EditProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Calendar/SheetCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Color/SheetColorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Sheets/Time/SheetTimeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/Common/DismissType.swift
  Projects/TDPresentation/Sources/Extension/UIViewController+NavigationBar.swift
  Projects/TDPresentation/Sources/Protocol/Coordinator.swift
  Projects/TDPresentation/Sources/Protocol/CoordinatorFinishDelegate.swift
Labels: 🐞 fix

#166 OIDC를 통한 Oauth 로그인 구현 with KAKAO, APPLE
  Projects/TDCore/Sources/JWTDecoder.swift
  Projects/TDData/Sources/Repository/AuthRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/AuthService.swift
  Projects/TDNetwork/Sources/Service/AuthServiceImpl.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewModel.swift
Labels: ✨ feature

#165 홈 탭바의 일정 생성&조회 API 연결
  Projects/TDCore/Sources/DIContainer.swift
  Projects/TDCore/Sources/Date+DateFormatType.swift
  Projects/TDCore/Sources/Date+StartEndDay.swift
  Projects/TDCore/Sources/TDDataError.swift
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDData/Sources/DTO/ScheduleRequestDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/PostRepositoryImpl.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/Repository/ScheduleRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/ScheduleService.swift
  Projects/TDDesign/Sources/Component/Button/TDSelectableButton.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDomain/Sources/Entity/Post.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/RepositoryProtocol/ScheduleRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/MoveTomorrowScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateScheduleUseCase.swift
  Projects/TDNetwork/Sources/Network/API/ScheduleAPI.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFSession.swift
  Projects/TDNetwork/Sources/Service/ScheduleServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Calendar/ToduckCalendarViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ViewModel/RoutineViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/Toduck/ToduckViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Profile/RoutineShareViewModel.swift
  Projects/TDPresentation/Sources/PresentModel/Event/EventDisplayItem.swift
Labels: ✨ feature

#172 #79 마이페이지 프로필 설정 디자인 완료
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Illust/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Illust/Withdraw.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Illust/Withdraw.imageset/Withdraw.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Illust/Withdraw.imageset/Withdraw@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Illust/Withdraw.imageset/Withdraw@3x.png
  Projects/TDDesign/Sources/Common/TDFont.swift
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/CheckBox/TDCheckBox.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextField.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextView.swift
  Projects/TDDesign/Sources/Component/TDLabel.swift
  Projects/TDDesign/Sources/Component/TextField/TDTextField.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Information/EditInformationCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Information/EditInformationView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Information/EditInformationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Menu/EditProfileMenuCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Menu/EditProfileMenuViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Password/EditPasswordCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Password/EditPasswordView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Password/EditPasswordViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Common/TDCheckboxField.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Completion/WithdrawCompletionViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Confirmation/WithdrawCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Confirmation/WithdrawView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Confirmation/WithdrawViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/ReasonInput/WithdrawReasonInputCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/ReasonInput/WithdrawReasonInputView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/ReasonInput/WithdrawReasonInputViewController.swift
  Projects/TDPresentation/Sources/Extension/UINavigationController+SetupNavigationBar.swift
Labels: ✨ feature

#173 일기 작성 & 수정 UI 구현
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Neutral_Color.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Neutral_Color.imageset/pen_Neutral_Color.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Neutral_Color.imageset/pen_Neutral_Color@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Neutral_Color.imageset/pen_Neutral_Color@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Primary_Color.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Primary_Color.imageset/pen_Primary_Color.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Primary_Color.imageset/pen_Primary_Color@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Pen/pen_Primary_Color.imageset/pen_Primary_Color@3x.png
  Projects/TDDesign/Sources/Common/TDFont.swift
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Button/TDBaseButton.swift
  Projects/TDDesign/Sources/Component/Category/TDCategoryCell.swift
  Projects/TDDesign/Sources/Component/Category/TDCategoryCollectionView.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryDetailView.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryMoodCell.swift
  Projects/TDDesign/Sources/Component/Diary/DiaryMoodCollectionView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormPhotoView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextField.swift
  Projects/TDDesign/Sources/Component/Form/TDFormTextView.swift
  Projects/TDDesign/Sources/Component/TDRequiredTitle.swift
  Projects/TDDesign/Sources/Component/TextField/TDTextField.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryEditType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryMakor/DiaryMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Home/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Withdraw/Common/TDCheckboxField.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/Extension/TDCategoryImageType+UIImage.swift
  Projects/TDPresentation/Sources/Extension/UIImage+Category.swift
  Projects/TDPresentation/Sources/Extension/UIImage+DiaryMood.swift
Labels: ✨ feature

#175 자체 회원가입 & 유저 아이디/비밀번호 찾기 API 연결
  Projects/TDData/Sources/DTO/FindIdResponseDTO.swift
  Projects/TDData/Sources/DTO/ScheduleListResponseDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/AuthRepositoryImpl.swift
  Projects/TDData/Sources/Repository/ScheduleRepositoryImpl.swift
  Projects/TDData/Sources/Repository/UserAuthRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/AuthService.swift
  Projects/TDData/Sources/ServiceProtocol/ScheduleService.swift
  Projects/TDData/Sources/ServiceProtocol/UserAuthService.swift
  Projects/TDDesign/Sources/Component/SegmentedControl/TDSegmentedControl.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/RegisterUser.swift
  Projects/TDDomain/Sources/RepositoryProtocol/AuthRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/UserAuthRepository.swift
  Projects/TDDomain/Sources/UseCase/ChangePasswordUseCase.swift
  Projects/TDDomain/Sources/UseCase/CheckDuplicateUserIDUseCase.swift
  Projects/TDDomain/Sources/UseCase/FindUserIdUseCase.swift
  Projects/TDDomain/Sources/UseCase/RegisterUserUseCase.swift
  Projects/TDDomain/Sources/UseCase/RequestPhoneVerificationCodeUseCase.swift
  Projects/TDDomain/Sources/UseCase/RequestVerificationCodeForFindUserUseCase.swift
  Projects/TDDomain/Sources/UseCase/RequestVerificationCodeForPasswordUseCase.swift
  Projects/TDDomain/Sources/UseCase/VerifyPhoneCodeUseCase.swift
  Projects/TDNetwork/Sources/Network/API/AuthAPI.swift
  Projects/TDNetwork/Sources/Network/API/UserAuthAPI.swift
  Projects/TDNetwork/Sources/Network/MF/MF/APIError.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFError.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFHTTPMethod.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFSession.swift
  Projects/TDNetwork/Sources/Network/MF/MF/ServerResponse.swift
  Projects/TDNetwork/Sources/Service/AuthServiceImpl.swift
  Projects/TDNetwork/Sources/Service/ScheduleServiceImpl.swift
  Projects/TDNetwork/Sources/Service/UserAuthServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindAccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/ShowIdViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/ChangePassword/ChangePasswordViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/ChangePassword/ChangePasswordViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignIn/SignInViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewModel.swift
  Projects/TDPresentation/Sources/Common/DismissType.swift
  Projects/TDPresentation/Sources/Protocol/Coordinator.swift
Labels: ✨ feature

#180 소셜 게시물 API 연결 (1)
  Projects/TDCore/Sources/Date+DateFormatType.swift
  Projects/TDData/Sources/DTO/PresignedUrlResponseDTO.swift
  Projects/TDData/Sources/DTO/TDPostDTO.swift
  Projects/TDData/Sources/DTO/TDRoutineDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/CommentRepositoryImpl.swift
  Projects/TDData/Sources/Repository/PostRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/AwsService.swift
  Projects/TDData/Sources/ServiceProtocol/SocialService.swift
  Projects/TDDesign/Sources/Component/Button/TDBaseButton.swift
  Projects/TDDesign/Sources/ViewControllers/TDPhotoPickerController.swift
  Projects/TDDomain/Sources/Entity/Comment.swift
  Projects/TDDomain/Sources/Entity/Enum/PostCategory.swift
  Projects/TDDomain/Sources/Entity/Post.swift
  Projects/TDDomain/Sources/Entity/User.swift
  Projects/TDDomain/Sources/RepositoryProtocol/PostRepository.swift
  Projects/TDDomain/Sources/UseCase/BlockPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/CreatePostUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeletePostUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/ReportPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/SearchPostUseCase.swift
  Projects/TDDomain/Sources/UseCase/TogglePostLikeUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdatePostUseCase.swift
  Projects/TDNetwork/Sources/Network/API/AwsAPI.swift
  Projects/TDNetwork/Sources/Network/API/SocialAPI.swift
  Projects/TDNetwork/Sources/Network/MF/Extensions/Extension+URLRequest.swift
  Projects/TDNetwork/Sources/Network/MF/MF/MFSession.swift
  Projects/TDNetwork/Sources/Service/AwsServiceImpl.swift
  Projects/TDNetwork/Sources/Service/SocialServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Delegates/SocialPostDelegate.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/SocialFeedMoreType.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialHeaderView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialImageListView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/Common/Views/SocialSelectCategoryView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/CreateView/SocialCreateViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/Cell/SocialDetailCommentCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/Cell/SocialDetailPostCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/DetailView/SocialDetailViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/Cell/SocialFeedCollectionViewCell.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Social/ListView/SocialListViewModel.swift
Labels: ✨ feature

#179 마이페이지와 일기에서 닉네임 조회 및 변경 API 연결
  Projects/TDData/Sources/DTO/UserNicknameResponseDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/MyPageRepositoryImpl.swift
  Projects/TDData/Sources/Repository/UserAuthRepositoryImpl.swift
  Projects/TDData/Sources/ServiceProtocol/MyPageService.swift
  Projects/TDData/Sources/ServiceProtocol/UserAuthService.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/RepositoryProtocol/MypageRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/UserAuthRepository.swift
  Projects/TDDomain/Sources/UseCase/FetchUserNicknameUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateUserNicknameUseCase.swift
  Projects/TDDomain/Sources/UseCase/UserLogoutUseCase.swift
  Projects/TDNetwork/Sources/Network/API/MyPageAPI.swift
  Projects/TDNetwork/Sources/Network/API/UserAuthAPI.swift
  Projects/TDNetwork/Sources/Service/MyPageServiceImpl.swift
  Projects/TDNetwork/Sources/Service/UserAuthServiceImpl.swift
  Projects/TDNetwork/Sources/ServiceAssembly.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindId/FindIdViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/FindAccount/FindPassword/FindPasswordViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/DiaryViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/Diary/View/DiaryAnalyzeView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/EditProfile/Profile/EditProfileViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MainPage/MyPageProfileView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageView.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MyPage/MyPageView/MyPageViewModel.swift
Labels: ✨ feature

#177 회원가입 성공 시 축하 화면으로 이동 & 로그인 성공 시 화면이동 코디네이터 관리
  Projects/TDDesign/Resources/Images.xcassets/Toduck/RegisterSuccess.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Toduck/RegisterSuccess.imageset/registerSuccess.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/RegisterSuccess.imageset/registerSuccess@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Toduck/RegisterSuccess.imageset/registerSuccess@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/RegisterSuccess/RegisterSuccessCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/RegisterSuccess/RegisterSuccessViewController.swift
Labels: ✨ feature
