Repository toduck-App/iOS-to.duck, pull requests merged in 2025-02, with the labels that each got.

#101 일정&루틴 Create 로직과 뷰 예외처리 보완
  Projects/TDData/Sources/Repository/PostRepositoryImpl.swift
  Projects/TDData/Sources/Repository/RoutineRepositoryImpl.swift
  Projects/TDData/Sources/Repository/ScheduleRepositoryImpl.swift
  Projects/TDDesign/Sources/Component/Form/TDFormButtonsView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormMoveView.swift
  Projects/TDDesign/Sources/Component/Form/TDFormSegmentView.swift
  Projects/TDDomain/Sources/Entity/Enum/AlarmType.swift
  Projects/TDDomain/Sources/Entity/Enum/TDWeekDay.swift
  Projects/TDDomain/Sources/Entity/Post.swift
  Projects/TDDomain/Sources/Entity/Protocol/Eventable.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDDomain/Sources/RepositoryProtocol/RoutineRepository.swift
  Projects/TDDomain/Sources/RepositoryProtocol/ScheduleRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/CreateScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/DeleteScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchRoutineListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleListUseCase.swift
  Projects/TDDomain/Sources/UseCase/FetchScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/MoveTomorrowScheduleUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateRoutineUseCase.swift
  Projects/TDDomain/Sources/UseCase/UpdateScheduleUseCase.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorView.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorViewModel.swift
  Projects/TDPresentation/Sources/Extension/Eventable+Presentation.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/RoutineViewModel.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/Sheets/Calendar/SheetCalendarCoordinator.swift
  Projects/TDPresentation/Sources/Sheets/Calendar/SheetCalendarDelegate.swift
  Projects/TDPresentation/Sources/Sheets/Calendar/SheetCalendarViewController.swift
  Projects/TDPresentation/Sources/Sheets/Color/SheetColorCoordinator.swift
  Projects/TDPresentation/Sources/Sheets/Color/SheetColorViewController.swift
  Projects/TDPresentation/Sources/Sheets/Time/SheetTimeCoordinator.swift
  Projects/TDPresentation/Sources/Sheets/Time/SheetTimeView.swift
  Projects/TDPresentation/Sources/Sheets/Time/SheetTimeViewController.swift
Labels: ✨ feature, 🖼️ design

#100 #98 집중 타이머 UI 및 기능
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/FocusCountRepositoryImpl.swift
  Projects/TDData/Sources/Repository/TimerRepositoryImpl.swift
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/tomato_Term.imageset/Vector 406.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/tomato_Term.imageset/Vector 406@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Small_Icons/tomato_Term.imageset/Vector 406@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Tomato/green_tomato.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Tomato/green_tomato.imageset/green_toamto.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/green_tomato.imageset/green_tomato@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/green_tomato.imageset/green_tomato@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/orange_tomato.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Tomato/orange_tomato.imageset/orange_tomato.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/orange_tomato.imageset/orange_tomato@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/orange_tomato.imageset/orange_tomato@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/timer_tomato.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Tomato/timer_tomato.imageset/timer_tomato.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/timer_tomato.imageset/timer_tomato@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/timer_tomato.imageset/timer_tomato@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/tomato.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Tomato/tomato.imageset/tomato.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/tomato.imageset/tomato@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Tomato/tomato.imageset/tomato@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Button/TDTimerButton.swift
  Projects/TDDesign/Sources/Component/TDToast.swift
  Projects/TDDesign/Sources/Component/Timer/TDToast.swift
  Projects/TDDesign/Sources/Component/Timer/TDToastView.swift
  Projects/TDDesign/Sources/Component/Timer/TDTomatoIconView.swift
  Projects/TDDesign/Sources/Component/Timer/TimerItemView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/TDTimerTheme.swift
  Projects/TDDomain/Sources/Entity/Timer.swift
  Projects/TDDomain/Sources/RepositoryProtocol/TimerRepository.swift
  Projects/TDDomain/Sources/UseCase/Timer/FetchFocusCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/FetchTimerSettingUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/FetchTimerThemeUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/TimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateFocusCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateTimerSettingUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateTimerThemeUseCase.swift
  Projects/TDPresentation/Sources/Protocol/TDToastPresentable.swift
  Projects/TDPresentation/Sources/Timer/Setting/TimerSettingView.swift
  Projects/TDPresentation/Sources/Timer/Setting/TimerSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/ThemeSetting/ThemeSettingView.swift
  Projects/TDPresentation/Sources/Timer/ThemeSetting/ThemeSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerCoordinator.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingView.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerView.swift
  Projects/TDPresentation/Sources/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerViewModel.swift
  Projects/TDPresentation/Sources/Timer/View/BboduckTimerView.swift
  Projects/TDPresentation/Sources/Timer/View/SimpleTimerView.swift
Labels: ✨ feature

#104 모듈 간 의존성 정리 및 불필요한 코드 제거
  .gitignore
  Projects/TDData/Project.swift
  Projects/TDNetwork/Project.swift
  Projects/TDPresentation/Sources/Social/Common/Views/SocialImageListView.swift
  Projects/TDPresentation/Sources/Social/Common/Views/UserProfileView.swift
  Projects/TDStorage/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/ProjectName.swift
  Tuist/ProjectDescriptionHelpers/ResourceExtensions.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+Module.swift
Labels: ♻️ refactor

#107 홈 탭바의 '토덕' 세그먼트 로티 및 컬렉션 뷰 UI 구현
  Projects/TDDesign/Resources/LottieJSON/toduckPower.json
  Projects/TDDesign/Resources/LottieJSON/toduckSleep.json
  Projects/TDDesign/Resources/LottieJSON/toduckStudy.json
  Projects/TDDesign/Sources/Component/SchduleAndRoutine/EventDetailView.swift
  Projects/TDDesign/Sources/Component/SegmentedControl/ScheduleSegmentedControl.swift
  Projects/TDDesign/Sources/Component/SegmentedControl/TDSegmentedControl.swift
  Projects/TDPresentation/Project.swift
  Projects/TDPresentation/Sources/Extension/TDCategoryImageType+UIImage.swift
  Projects/TDPresentation/Sources/Home/HomeViewController.swift
  Projects/TDPresentation/Sources/Home/Toduck/ScheduleCollectionViewCell.swift
  Projects/TDPresentation/Sources/Home/Toduck/ScheduleListView.swift
  Projects/TDPresentation/Sources/Home/Toduck/ToduckView.swift
  Projects/TDPresentation/Sources/Home/Toduck/ToduckViewController.swift
  Projects/TDPresentation/Sources/Home/Toduck/ToduckViewModel.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListView.swift
  Projects/TDPresentation/Sources/Social/Profile/SocialProfileView.swift
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+External.swift
Labels: ✨ feature

#111 집중 타이머 Setting UserDefualts 구성 #105
  Projects/TDData/Sources/DTO/TDTimerFocusCountDTO.swift
  Projects/TDData/Sources/DTO/TDTimerSettingDTO.swift
  Projects/TDData/Sources/DTO/TDTimerThemeDTO.swift
  Projects/TDData/Sources/DataAssembly.swift
  Projects/TDData/Sources/Repository/TimerRepositoryImpl.swift
  Projects/TDData/Sources/StorageProtocol/TimerStorage.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/Entity/Enum/TDTimerTheme.swift
  Projects/TDDomain/Sources/Entity/Timer.swift
  Projects/TDDomain/Sources/RepositoryProtocol/TimerRepository.swift
  Projects/TDDomain/Sources/UseCase/Timer/ResetFocusCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/TimerUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateFocusCountUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateTimerSettingUseCase.swift
  Projects/TDPresentation/Sources/Timer/TimerCoordinator.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingView.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerViewModel.swift
  Projects/TDStorage/Sources/StorageAssembly.swift
  Projects/TDStorage/Sources/UserDefaults/TimerStorage.swift
Labels: ✨ feature

#115 홈 탭바 - 일정&루틴 셀에서 우측 스와이프 삭제 UI 구현
  Projects/TDDesign/Resources/Images.xcassets/Alert/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Alert/delete_Event.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Alert/delete_Event.imageset/delete_Event.png
  Projects/TDDesign/Resources/Images.xcassets/Alert/delete_Event.imageset/delete_Event@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Alert/delete_Event.imageset/delete_Event@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDomain/Sources/Entity/Protocol/Eventable.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDPresentation/Sources/Common/TDPopupViewController.swift
  Projects/TDPresentation/Sources/Home/Alert/DeleteEventView.swift
  Projects/TDPresentation/Sources/Home/Alert/DeleteEventViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/Cell/TimeSlotTableViewCell.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/PresentModel/Event/EventDisplayItem.swift
  Projects/TDPresentation/Sources/PresentModel/Event/EventPresentable.swift
  Projects/TDPresentation/Sources/PresentModel/TimeSlot/TimeSlotProvider.swift
  Projects/TDPresentation/Sources/Social/Block/SocialBlockViewController.swift
Labels: ✨ feature

#117 집중 타이머 테마 변경 시트뷰 #112
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Calendar/calendar_Top2_Medium_Orange.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Calendar/calendar_Top2_Medium_Orange.imageset/calendar_Top2_Medium_Orange.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Calendar/calendar_Top2_Medium_Orange.imageset/calendar_Top2_Medium_Orange@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Medium_Icons/Calendar/calendar_Top2_Medium_Orange.imageset/calendar_Top2_Medium_Orange@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Bboduck_Preview.imageset/BboduckPreview.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Bboduck_Preview.imageset/BboduckPreview@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Bboduck_Preview.imageset/BboduckPreview@3x.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Bboduck_Preview.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Simple_Preview.imageset/Contents.json
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Simple_Preview.imageset/SimplePreview.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Simple_Preview.imageset/SimplePreview@2x.png
  Projects/TDDesign/Resources/Images.xcassets/Theme_Previews/Simple_Preview.imageset/SimplePreview@3x.png
  Projects/TDDesign/Sources/Common/TDImage.swift
  Projects/TDDesign/Sources/Component/Dropdown/TDDropdownHoverView.swift
  Projects/TDDomain/Sources/DomainAssembly.swift
  Projects/TDDomain/Sources/UseCase/Timer/FetchTimerThemeUseCase.swift
  Projects/TDDomain/Sources/UseCase/Timer/UpdateTimerThemeUseCase.swift
  Projects/TDPresentation/Sources/Timer/ThemeSetting/ThemeItemControl.swift
  Projects/TDPresentation/Sources/Timer/ThemeSetting/ThemeSettingView.swift
  Projects/TDPresentation/Sources/Timer/ThemeSetting/ThemeSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerCoordinator.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingFieldControl.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingView.swift
  Projects/TDPresentation/Sources/Timer/TimerSetting/TimerSettingViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerView.swift
  Projects/TDPresentation/Sources/Timer/TimerViewController.swift
  Projects/TDPresentation/Sources/Timer/TimerViewModel.swift
Labels: ✨ feature

#118 홈 탭바 - 일정&루틴 셀 클릭 시 상세보기 화면으로 이동
  Projects/TDDesign/Sources/Component/Form/TDFormMoveView.swift
  Projects/TDDesign/Sources/Component/TDRequiredTitle.swift
  Projects/TDDomain/Sources/Entity/Enum/AlarmType.swift
  Projects/TDDomain/Sources/Entity/Enum/TDWeekDay.swift
  Projects/TDDomain/Sources/Entity/Routine.swift
  Projects/TDDomain/Sources/Entity/Schedule.swift
  Projects/TDPresentation/Sources/Alert/DeleteEvent/DeleteEventView.swift
  Projects/TDPresentation/Sources/Alert/DeleteEvent/DeleteEventViewController.swift
  Projects/TDPresentation/Sources/Alert/DetailEvent/DetailEventView.swift
  Projects/TDPresentation/Sources/Alert/DetailEvent/DetailEventViewController.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorCoordinator.swift
  Projects/TDPresentation/Sources/EventMakor/EventMakorViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ScheduleAndRoutineViewController.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/RoutineViewModel.swift
  Projects/TDPresentation/Sources/Home/ScheduleAndRoutine/ViewModel/ScheduleViewModel.swift
  Projects/TDPresentation/Sources/PresentModel/Event/EventDisplayItem.swift
Labels: ✨ feature

#121 프로젝트 내에 런치 스크린 추가 및 설정
  Projects/toduck/Resources/Assets.xcassets/launchScreenImage.imageset/Contents.json
  Projects/toduck/Resources/Assets.xcassets/launchScreenImage.imageset/toduck_Logo.png
  Projects/toduck/Resources/Assets.xcassets/launchScreenImage.imageset/toduck_Logo@2x.png
  Projects/toduck/Resources/Assets.xcassets/launchScreenImage.imageset/toduck_Logo@3x.png
  Projects/toduck/Resources/LaunchScreen.storyboard
  Projects/toduck/SupportingFiles/Info.plist
Labels: ✨ feature

#126 회원가입에 필요한 휴대폰 인증 + 회원정보 입력 UI 구현
  Projects/TDDesign/Sources/Component/Dropdown/TDDropdownHoverView.swift
  Projects/TDPresentation/Sources/AppFlow/AppCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/AuthViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/Account/AccountViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/CarrierDropDownMenuItem.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationView.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewController.swift
  Projects/TDPresentation/Sources/AppFlow/AuthFlow/SignUp/PhoneVerification/PhoneVerificationViewModel.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarController.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabBarCoordinator.swift
  Projects/TDPresentation/Sources/AppFlow/MainFlow/MainTabbarItem.swift
  Projects/TDPresentation/Sources/Calendar/ToduckCalendarCoordinator.swift
  Projects/TDPresentation/Sources/Diary/DiaryCoordinator.swift
  Projects/TDPresentation/Sources/Home/HomeCoordinator.swift
  Projects/TDPresentation/Sources/MyPage/MyPageCoordinator.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListCoordinator.swift
  Projects/TDPresentation/Sources/Social/ListView/SocialListDropdownView.swift
  Projects/TDPresentation/Sources/Timer/TimerCoordinator.swift
Labels: ✨ feature, 🖼️ design

#124 Feat: 댓글 작성 기능, 추가
  Projects/TDData/Sources/Repository/CommentRepositoryImpl.swift
  Projects/TDDesign/Sources/ViewControllers/TDPhotoPickerController.swift
  Projects/TDDomain/Sources/Entity/Comment.swift
  Projects/TDDomain/Sources/Entity/Enum/NewComment.swift
  Projects/TDDomain/Sources/RepositoryProtocol/CommentRepository.swift
  Projects/TDDomain/Sources/UseCase/CreateCommentUseCase.swift
  Projects/TDPresentation/Sources/Extension/NavigationController+PushViewController.swift
  Projects/TDPresentation/Sources/Social/Common/Views/SocialFooterView.swift
  Projects/TDPresentation/Sources/Social/Common/Views/SocialImageListView.swift
  Projects/TDPresentation/Sources/Social/DetailView/Cell/SocialDetailCommentCell.swift
  Projects/TDPresentation/Sources/Social/DetailView/Cell/SocialDetailPostCell.swift
  Projects/TDPresentation/Sources/Social/DetailView/CommentImageView.swift
  Projects/TDPresentation/Sources/Social/DetailView/CommentInputForm.swift
  Projects/TDPresentation/Sources/Social/DetailView/CommentReplyView.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailView.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailViewController.swift
  Projects/TDPresentation/Sources/Social/DetailView/SocialDetailViewModel.swift
  Projects/TDPresentation/Sources/Social/ListView/Cell/SocialFeedCollectionViewCell.swift
Labels: ✨ feature, 🖼️ design
